/**
 * Created by ibm on 2017/6/10.
 */
module.exports= {
    entry:{
        bundle:"./src/index.js"
    },
    output:{
        path:__dirname+"/build",
        filename:"[name].js"
    },
    module:{
        rules:[
            {
                test:/\.css$/,
                use:[
                    {
                        loader:"style-loader"
                    },
                    {
                        loader:"css-loader"
                    }
                ]
            },{
                test:/\.sass$/,
                use:[
                    {
                        loader:"style-loader"
                    },
                    {
                        loader:"css-loader"
                    },
                    {
                        loader:"sass-loader"
                    }
                ]
            },{
                test:/\.png|jpg$/,
                use:[
                    {
                        loader:"url-loader"
                    }
                ]
            },
            {
                test:/\.js$/,
                use:[
                    {
                        loader:"babel-loader",
                    }
                ]
            },
            {
                test:/\.vue$/,
                use:[
                    {
                        loader:"vue-loader"
                    }
                ]
            }
        ]
    }
}